version: "3.9"

services:
  spark:
    build: .
    container_name: spark_ventas
    volumes:
      - ./procesar_ventas.py:/app/procesar_ventas.py
      - ./hecho_ventas.csv:/app/hecho_ventas.csv
    working_dir: /app
    command: tail -f /dev/null  
